/**
 * Maps ISO_A2 country codes to internal country slugs.
 * Generated from gayanvoice/top-github-users country list.
 */
export const ISO_TO_COUNTRY: Record<string, string> = {
  AF: "afghanistan",
  AL: "albania",
  DZ: "algeria",
  AD: "andorra",
  AO: "angola",
  AR: "argentina",
  AM: "armenia",
  AU: "australia",
  AT: "austria",
  AZ: "azerbaijan",
  BH: "bahrain",
  BD: "bangladesh",
  BY: "belarus",
  BE: "belgium",
  BJ: "benin",
  BT: "bhutan",
  BO: "bolivia",
  BA: "bosnia-and-herzegovina",
  BW: "botswana",
  BR: "brazil",
  BG: "bulgaria",
  BF: "burkina-faso",
  BI: "burundi",
  KH: "cambodia",
  CM: "cameroon",
  CA: "canada",
  TD: "chad",
  CL: "chile",
  CN: "china",
  HK: "hong-kong",
  TW: "taiwan",
  CO: "colombia",
  CG: "congo",
  HR: "croatia",
  CU: "cuba",
  CY: "cyprus",
  CZ: "czechia",
  DK: "denmark",
  DO: "dominican-republic",
  EC: "ecuador",
  EG: "egypt",
  SV: "el-salvador",
  EE: "estonia",
  ET: "ethiopia",
  FI: "finland",
  FR: "france",
  GE: "georgia",
  DE: "germany",
  GH: "ghana",
  GR: "greece",
  GT: "guatemala",
  HN: "honduras",
  HU: "hungary",
  IS: "iceland",
  IN: "india",
  ID: "indonesia",
  IR: "iran",
  IQ: "iraq",
  IE: "ireland",
  IL: "israel",
  IT: "italy",
  JM: "jamaica",
  JP: "japan",
  JO: "jordan",
  KZ: "kazakhstan",
  KE: "kenya",
  KW: "kuwait",
  LA: "laos",
  LV: "latvia",
  LT: "lithuania",
  LU: "luxembourg",
  MG: "madagascar",
  MW: "malawi",
  MY: "malaysia",
  MV: "maldives",
  ML: "mali",
  MT: "malta",
  MU: "mauritius",
  MX: "mexico",
  MD: "moldova",
  MN: "mongolia",
  ME: "montenegro",
  MA: "morocco",
  MZ: "mozambique",
  MM: "myanmar",
  NA: "namibia",
  NP: "nepal",
  NL: "netherlands",
  NZ: "new-zealand",
  NI: "nicaragua",
  NG: "nigeria",
  NO: "norway",
  OM: "oman",
  PK: "pakistan",
  PS: "palestine",
  PA: "panama",
  PY: "paraguay",
  PE: "peru",
  PH: "philippines",
  PL: "poland",
  PT: "portugal",
  QA: "qatar",
  RO: "romania",
  RU: "russia",
  RW: "rwanda",
  SA: "saudi-arabia",
  SN: "senegal",
  RS: "serbia",
  SG: "singapore",
  SK: "slovakia",
  SI: "slovenia",
  ZA: "south-africa",
  KR: "south-korea",
  ES: "spain",
  LK: "sri-lanka",
  SD: "sudan",
  SE: "sweden",
  CH: "switzerland",
  SY: "syria",
  TZ: "tanzania",
  TH: "thailand",
  TN: "tunisia",
  TR: "turkey",
  UG: "uganda",
  UA: "ukraine",
  AE: "united-arab-emirates",
  GB: "united-kingdom",
  US: "united-states",
  UY: "uruguay",
  UZ: "uzbekistan",
  VE: "venezuela",
  VN: "vietnam",
  ZM: "zambia",
  ZW: "zimbabwe",
};

export function getIsoCode(properties: Record<string, string>): string {
  const iso = properties.ISO_A2;
  if (iso && iso !== "-99" && !iso.includes("-")) return iso;
  return properties.ISO_A2_EH ?? iso;
}

export function isConfiguredCountry(isoA2: string): boolean {
  return isoA2 in ISO_TO_COUNTRY;
}

export function getCountrySlug(isoA2: string): string | null {
  return ISO_TO_COUNTRY[isoA2] ?? null;
}
