import fs from "node:fs";
import path from "node:path";

interface CountryDef {
  code: string;
  name: string;
  flag: string;
  iso: string;
  locations: string[];
  region: string;
}

// All 195 countries with ISO codes, flags, and regions for name generation
const countries: CountryDef[] = [
  // From gayanvoice/top-github-users config (138 countries)
  {
    code: "afghanistan",
    name: "Afghanistan",
    flag: "\u{1F1E6}\u{1F1EB}",
    iso: "AF",
    locations: [
      "Afghanistan",
      "Kabul",
      "Kandahar",
      "Herat",
      "Kunduz",
      "Lashkargah",
      "Ghazni",
      "Khost",
    ],
    region: "south-asia",
  },
  {
    code: "albania",
    name: "Albania",
    flag: "\u{1F1E6}\u{1F1F1}",
    iso: "AL",
    locations: [
      "Albania",
      "Tirana",
      "Durr\u00ebs",
      "Vlor\u00eb",
      "Elbasan",
      "Shkod\u00ebr",
    ],
    region: "europe",
  },
  {
    code: "algeria",
    name: "Algeria",
    flag: "\u{1F1E9}\u{1F1FF}",
    iso: "DZ",
    locations: [
      "Algeria",
      "Algiers",
      "Oran",
      "Constantine",
      "Batna",
      "S\u00e9tif",
      "Annaba",
    ],
    region: "arab",
  },
  {
    code: "andorra",
    name: "Andorra",
    flag: "\u{1F1E6}\u{1F1E9}",
    iso: "AD",
    locations: ["Andorra", "Andorra la Vella", "Santa Coloma", "La Margineda"],
    region: "europe",
  },
  {
    code: "angola",
    name: "Angola",
    flag: "\u{1F1E6}\u{1F1F4}",
    iso: "AO",
    locations: [
      "Angola",
      "Luanda",
      "Cabinda",
      "Huambo",
      "Lubango",
      "Lobito",
      "Benguela",
    ],
    region: "africa",
  },
  {
    code: "argentina",
    name: "Argentina",
    flag: "\u{1F1E6}\u{1F1F7}",
    iso: "AR",
    locations: [
      "Argentina",
      "Buenos Aires",
      "C\u00f3rdoba",
      "Rosario",
      "La Plata",
      "Tucum\u00e1n",
      "Mar del Plata",
      "Salta",
    ],
    region: "latin-america",
  },
  {
    code: "armenia",
    name: "Armenia",
    flag: "\u{1F1E6}\u{1F1F2}",
    iso: "AM",
    locations: ["Armenia", "Yerevan", "Gyumri", "Vanadzor", "Vagharshapat"],
    region: "europe",
  },
  {
    code: "australia",
    name: "Australia",
    flag: "\u{1F1E6}\u{1F1FA}",
    iso: "AU",
    locations: [
      "Australia",
      "Sydney",
      "Melbourne",
      "Perth",
      "Adelaide",
      "Brisbane",
      "Canberra",
      "Hobart",
    ],
    region: "english",
  },
  {
    code: "austria",
    name: "Austria",
    flag: "\u{1F1E6}\u{1F1F9}",
    iso: "AT",
    locations: ["Austria", "Vienna", "Salzburg", "Innsbruck", "Linz", "Graz"],
    region: "german",
  },
  {
    code: "azerbaijan",
    name: "Azerbaijan",
    flag: "\u{1F1E6}\u{1F1FF}",
    iso: "AZ",
    locations: ["Azerbaijan", "Baku", "Ganja", "Sumqayit", "Mingecevir"],
    region: "turkic",
  },
  {
    code: "bahrain",
    name: "Bahrain",
    flag: "\u{1F1E7}\u{1F1ED}",
    iso: "BH",
    locations: ["Bahrain", "Riffa", "Muharraq"],
    region: "arab",
  },
  {
    code: "bangladesh",
    name: "Bangladesh",
    flag: "\u{1F1E7}\u{1F1E9}",
    iso: "BD",
    locations: [
      "Bangladesh",
      "Dhaka",
      "Mymensingh",
      "Rajshahi",
      "Rangpur",
      "Chittagong",
      "Khulna",
    ],
    region: "south-asia",
  },
  {
    code: "belarus",
    name: "Belarus",
    flag: "\u{1F1E7}\u{1F1FE}",
    iso: "BY",
    locations: ["Belarus", "Minsk", "Gomel", "Grodno", "Mogilev", "Brest"],
    region: "slavic",
  },
  {
    code: "belgium",
    name: "Belgium",
    flag: "\u{1F1E7}\u{1F1EA}",
    iso: "BE",
    locations: [
      "Belgium",
      "Antwerp",
      "Brussels",
      "Ghent",
      "Bruges",
      "Leuven",
      "Li\u00e8ge",
    ],
    region: "europe",
  },
  {
    code: "benin",
    name: "Benin",
    flag: "\u{1F1E7}\u{1F1EF}",
    iso: "BJ",
    locations: ["Benin", "Cotonou", "Porto-Novo", "Parakou", "Kandi"],
    region: "africa",
  },
  {
    code: "bhutan",
    name: "Bhutan",
    flag: "\u{1F1E7}\u{1F1F9}",
    iso: "BT",
    locations: ["Bhutan", "Thimphu", "Phuntsholing", "Gelephu"],
    region: "south-asia",
  },
  {
    code: "bolivia",
    name: "Bolivia",
    flag: "\u{1F1E7}\u{1F1F4}",
    iso: "BO",
    locations: [
      "Bolivia",
      "La Paz",
      "Cochabamba",
      "Santa Cruz de la Sierra",
      "Sucre",
      "El Alto",
    ],
    region: "latin-america",
  },
  {
    code: "bosnia-and-herzegovina",
    name: "Bosnia and Herzegovina",
    flag: "\u{1F1E7}\u{1F1E6}",
    iso: "BA",
    locations: [
      "Bosnia and Herzegovina",
      "Sarajevo",
      "Mostar",
      "Tuzla",
      "Zenica",
    ],
    region: "slavic",
  },
  {
    code: "botswana",
    name: "Botswana",
    flag: "\u{1F1E7}\u{1F1FC}",
    iso: "BW",
    locations: ["Botswana", "Gaborone", "Francistown", "Maun", "Serowe"],
    region: "africa",
  },
  {
    code: "brazil",
    name: "Brazil",
    flag: "\u{1F1E7}\u{1F1F7}",
    iso: "BR",
    locations: [
      "Brazil",
      "S\u00e3o Paulo",
      "Rio de Janeiro",
      "Belo Horizonte",
      "Curitiba",
      "Bras\u00edlia",
      "Fortaleza",
      "Manaus",
    ],
    region: "portuguese",
  },
  {
    code: "bulgaria",
    name: "Bulgaria",
    flag: "\u{1F1E7}\u{1F1EC}",
    iso: "BG",
    locations: ["Bulgaria", "Sofia", "Varna", "Plovdiv", "Ruse"],
    region: "slavic",
  },
  {
    code: "burkina-faso",
    name: "Burkina Faso",
    flag: "\u{1F1E7}\u{1F1EB}",
    iso: "BF",
    locations: ["Burkina Faso", "Ouagadougou", "Bobo-Dioulasso", "Koudougou"],
    region: "africa",
  },
  {
    code: "burundi",
    name: "Burundi",
    flag: "\u{1F1E7}\u{1F1EE}",
    iso: "BI",
    locations: ["Burundi", "Bujumbura", "Gitega", "Muyinga", "Ngozi"],
    region: "africa",
  },
  {
    code: "cambodia",
    name: "Cambodia",
    flag: "\u{1F1F0}\u{1F1ED}",
    iso: "KH",
    locations: ["Cambodia", "Phnom Penh", "Siem Reap", "Battambang"],
    region: "southeast-asia",
  },
  {
    code: "cameroon",
    name: "Cameroon",
    flag: "\u{1F1E8}\u{1F1F2}",
    iso: "CM",
    locations: ["Cameroon", "Yaound\u00e9", "Douala", "Bamenda", "Garoua"],
    region: "africa",
  },
  {
    code: "canada",
    name: "Canada",
    flag: "\u{1F1E8}\u{1F1E6}",
    iso: "CA",
    locations: [
      "Canada",
      "Toronto",
      "Montreal",
      "Vancouver",
      "Calgary",
      "Edmonton",
      "Ottawa",
      "Winnipeg",
    ],
    region: "english",
  },
  {
    code: "chad",
    name: "Chad",
    flag: "\u{1F1F9}\u{1F1E9}",
    iso: "TD",
    locations: ["Chad", "N'Djamena", "Moundou", "Sarh"],
    region: "africa",
  },
  {
    code: "chile",
    name: "Chile",
    flag: "\u{1F1E8}\u{1F1F1}",
    iso: "CL",
    locations: [
      "Chile",
      "Santiago",
      "Valpara\u00edso",
      "Concepci\u00f3n",
      "Temuco",
    ],
    region: "latin-america",
  },
  {
    code: "china",
    name: "China",
    flag: "\u{1F1E8}\u{1F1F3}",
    iso: "CN",
    locations: [
      "China",
      "Beijing",
      "Shanghai",
      "Guangzhou",
      "Shenzhen",
      "Chengdu",
      "Hangzhou",
      "Nanjing",
    ],
    region: "chinese",
  },
  {
    code: "hong-kong",
    name: "Hong Kong",
    flag: "\u{1F1ED}\u{1F1F0}",
    iso: "HK",
    locations: ["Hong Kong", "Kowloon"],
    region: "chinese",
  },
  {
    code: "taiwan",
    name: "Taiwan",
    flag: "\u{1F1F9}\u{1F1FC}",
    iso: "TW",
    locations: [
      "Taiwan",
      "Taipei",
      "Kaohsiung",
      "Taichung",
      "Tainan",
      "Hsinchu",
    ],
    region: "chinese",
  },
  {
    code: "colombia",
    name: "Colombia",
    flag: "\u{1F1E8}\u{1F1F4}",
    iso: "CO",
    locations: [
      "Colombia",
      "Bogot\u00e1",
      "Medell\u00edn",
      "Cali",
      "Cartagena",
      "Barranquilla",
    ],
    region: "latin-america",
  },
  {
    code: "congo",
    name: "Congo",
    flag: "\u{1F1E8}\u{1F1EC}",
    iso: "CG",
    locations: ["Congo", "Brazzaville", "Pointe-Noire"],
    region: "africa",
  },
  {
    code: "croatia",
    name: "Croatia",
    flag: "\u{1F1ED}\u{1F1F7}",
    iso: "HR",
    locations: ["Croatia", "Zagreb", "Split", "Dubrovnik", "Rijeka", "Osijek"],
    region: "slavic",
  },
  {
    code: "cuba",
    name: "Cuba",
    flag: "\u{1F1E8}\u{1F1FA}",
    iso: "CU",
    locations: ["Cuba", "Havana", "Santiago de Cuba"],
    region: "latin-america",
  },
  {
    code: "cyprus",
    name: "Cyprus",
    flag: "\u{1F1E8}\u{1F1FE}",
    iso: "CY",
    locations: ["Cyprus", "Nicosia", "Limassol", "Larnaca", "Paphos"],
    region: "europe",
  },
  {
    code: "czechia",
    name: "Czechia",
    flag: "\u{1F1E8}\u{1F1FF}",
    iso: "CZ",
    locations: ["Czechia", "Prague", "Brno", "Ostrava", "Pilsen", "Olomouc"],
    region: "slavic",
  },
  {
    code: "denmark",
    name: "Denmark",
    flag: "\u{1F1E9}\u{1F1F0}",
    iso: "DK",
    locations: ["Denmark", "Copenhagen", "Aarhus", "Aalborg", "Odense"],
    region: "nordic",
  },
  {
    code: "dominican-republic",
    name: "Dominican Republic",
    flag: "\u{1F1E9}\u{1F1F4}",
    iso: "DO",
    locations: [
      "Dominican Republic",
      "Santo Domingo",
      "Santiago de los Caballeros",
      "Puerto Plata",
    ],
    region: "latin-america",
  },
  {
    code: "ecuador",
    name: "Ecuador",
    flag: "\u{1F1EA}\u{1F1E8}",
    iso: "EC",
    locations: ["Ecuador", "Quito", "Guayaquil", "Cuenca", "Ambato"],
    region: "latin-america",
  },
  {
    code: "egypt",
    name: "Egypt",
    flag: "\u{1F1EA}\u{1F1EC}",
    iso: "EG",
    locations: ["Egypt", "Cairo", "Alexandria", "Giza", "Luxor", "Aswan"],
    region: "arab",
  },
  {
    code: "el-salvador",
    name: "El Salvador",
    flag: "\u{1F1F8}\u{1F1FB}",
    iso: "SV",
    locations: ["El Salvador", "San Salvador", "San Miguel", "Santa Ana"],
    region: "latin-america",
  },
  {
    code: "estonia",
    name: "Estonia",
    flag: "\u{1F1EA}\u{1F1EA}",
    iso: "EE",
    locations: ["Estonia", "Tallinn", "Tartu", "P\u00e4rnu", "Narva"],
    region: "baltic",
  },
  {
    code: "ethiopia",
    name: "Ethiopia",
    flag: "\u{1F1EA}\u{1F1F9}",
    iso: "ET",
    locations: ["Ethiopia", "Addis Ababa", "Dire Dawa", "Hawassa", "Dessie"],
    region: "africa",
  },
  {
    code: "finland",
    name: "Finland",
    flag: "\u{1F1EB}\u{1F1EE}",
    iso: "FI",
    locations: ["Finland", "Helsinki", "Tampere", "Oulu", "Espoo", "Vantaa"],
    region: "nordic",
  },
  {
    code: "france",
    name: "France",
    flag: "\u{1F1EB}\u{1F1F7}",
    iso: "FR",
    locations: [
      "France",
      "Paris",
      "Lyon",
      "Toulouse",
      "Marseille",
      "Bordeaux",
      "Strasbourg",
      "Nice",
      "Nantes",
    ],
    region: "french",
  },
  {
    code: "georgia",
    name: "Georgia",
    flag: "\u{1F1EC}\u{1F1EA}",
    iso: "GE",
    locations: ["Georgia", "Tbilisi", "Batumi", "Kutaisi", "Rustavi"],
    region: "europe",
  },
  {
    code: "germany",
    name: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    iso: "DE",
    locations: [
      "Germany",
      "Berlin",
      "Munich",
      "Hamburg",
      "Frankfurt",
      "Cologne",
      "Stuttgart",
      "D\u00fcsseldorf",
      "Dresden",
    ],
    region: "german",
  },
  {
    code: "ghana",
    name: "Ghana",
    flag: "\u{1F1EC}\u{1F1ED}",
    iso: "GH",
    locations: ["Ghana", "Accra", "Kumasi", "Sekondi-Takoradi", "Tamale"],
    region: "africa",
  },
  {
    code: "greece",
    name: "Greece",
    flag: "\u{1F1EC}\u{1F1F7}",
    iso: "GR",
    locations: ["Greece", "Athens", "Thessaloniki", "Patras", "Heraklion"],
    region: "europe",
  },
  {
    code: "guatemala",
    name: "Guatemala",
    flag: "\u{1F1EC}\u{1F1F9}",
    iso: "GT",
    locations: [
      "Guatemala",
      "Guatemala City",
      "Quetzaltenango",
      "Antigua Guatemala",
    ],
    region: "latin-america",
  },
  {
    code: "honduras",
    name: "Honduras",
    flag: "\u{1F1ED}\u{1F1F3}",
    iso: "HN",
    locations: [
      "Honduras",
      "Tegucigalpa",
      "San Pedro Sula",
      "La Ceiba",
      "Comayagua",
    ],
    region: "latin-america",
  },
  {
    code: "hungary",
    name: "Hungary",
    flag: "\u{1F1ED}\u{1F1FA}",
    iso: "HU",
    locations: [
      "Hungary",
      "Budapest",
      "Debrecen",
      "Szeged",
      "Miskolc",
      "P\u00e9cs",
    ],
    region: "europe",
  },
  {
    code: "iceland",
    name: "Iceland",
    flag: "\u{1F1EE}\u{1F1F8}",
    iso: "IS",
    locations: ["Iceland", "Reykjav\u00edk", "K\u00f3pavogur", "Akureyri"],
    region: "nordic",
  },
  {
    code: "india",
    name: "India",
    flag: "\u{1F1EE}\u{1F1F3}",
    iso: "IN",
    locations: [
      "India",
      "Bangalore",
      "Mumbai",
      "Delhi",
      "Hyderabad",
      "Pune",
      "Chennai",
      "Kolkata",
    ],
    region: "south-asia",
  },
  {
    code: "indonesia",
    name: "Indonesia",
    flag: "\u{1F1EE}\u{1F1E9}",
    iso: "ID",
    locations: [
      "Indonesia",
      "Jakarta",
      "Bandung",
      "Surabaya",
      "Makassar",
      "Medan",
      "Semarang",
    ],
    region: "southeast-asia",
  },
  {
    code: "iran",
    name: "Iran",
    flag: "\u{1F1EE}\u{1F1F7}",
    iso: "IR",
    locations: ["Iran", "Tehran", "Isfahan", "Tabriz", "Shiraz", "Mashhad"],
    region: "persian",
  },
  {
    code: "iraq",
    name: "Iraq",
    flag: "\u{1F1EE}\u{1F1F6}",
    iso: "IQ",
    locations: ["Iraq", "Baghdad", "Mosul", "Basra", "Erbil", "Najaf"],
    region: "arab",
  },
  {
    code: "ireland",
    name: "Ireland",
    flag: "\u{1F1EE}\u{1F1EA}",
    iso: "IE",
    locations: ["Ireland", "Dublin", "Galway", "Cork", "Limerick"],
    region: "english",
  },
  {
    code: "israel",
    name: "Israel",
    flag: "\u{1F1EE}\u{1F1F1}",
    iso: "IL",
    locations: ["Israel", "Jerusalem", "Tel Aviv", "Haifa", "Be'er Sheva"],
    region: "hebrew",
  },
  {
    code: "italy",
    name: "Italy",
    flag: "\u{1F1EE}\u{1F1F9}",
    iso: "IT",
    locations: [
      "Italy",
      "Rome",
      "Milan",
      "Naples",
      "Turin",
      "Florence",
      "Bologna",
      "Venice",
    ],
    region: "italian",
  },
  {
    code: "jamaica",
    name: "Jamaica",
    flag: "\u{1F1EF}\u{1F1F2}",
    iso: "JM",
    locations: ["Jamaica", "Kingston", "Montego Bay", "Ocho Rios"],
    region: "english",
  },
  {
    code: "japan",
    name: "Japan",
    flag: "\u{1F1EF}\u{1F1F5}",
    iso: "JP",
    locations: ["Japan", "Tokyo", "Osaka", "Kyoto", "Fukuoka", "Nagoya"],
    region: "japanese",
  },
  {
    code: "jordan",
    name: "Jordan",
    flag: "\u{1F1EF}\u{1F1F4}",
    iso: "JO",
    locations: ["Jordan", "Amman", "Aqaba", "Zarqa", "Irbid"],
    region: "arab",
  },
  {
    code: "kazakhstan",
    name: "Kazakhstan",
    flag: "\u{1F1F0}\u{1F1FF}",
    iso: "KZ",
    locations: ["Kazakhstan", "Almaty", "Astana", "Shymkent", "Karagandy"],
    region: "turkic",
  },
  {
    code: "kenya",
    name: "Kenya",
    flag: "\u{1F1F0}\u{1F1EA}",
    iso: "KE",
    locations: ["Kenya", "Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
    region: "africa",
  },
  {
    code: "kuwait",
    name: "Kuwait",
    flag: "\u{1F1F0}\u{1F1FC}",
    iso: "KW",
    locations: ["Kuwait", "Kuwait City", "Al Jahra", "Salmiya"],
    region: "arab",
  },
  {
    code: "laos",
    name: "Laos",
    flag: "\u{1F1F1}\u{1F1E6}",
    iso: "LA",
    locations: ["Laos", "Vientiane"],
    region: "southeast-asia",
  },
  {
    code: "latvia",
    name: "Latvia",
    flag: "\u{1F1F1}\u{1F1FB}",
    iso: "LV",
    locations: ["Latvia", "Riga", "Daugavpils", "Liep\u0101ja", "Jelgava"],
    region: "baltic",
  },
  {
    code: "lithuania",
    name: "Lithuania",
    flag: "\u{1F1F1}\u{1F1F9}",
    iso: "LT",
    locations: [
      "Lithuania",
      "Vilnius",
      "Kaunas",
      "Klaip\u0117da",
      "\u0160iauliai",
    ],
    region: "baltic",
  },
  {
    code: "luxembourg",
    name: "Luxembourg",
    flag: "\u{1F1F1}\u{1F1FA}",
    iso: "LU",
    locations: ["Luxembourg", "Luxembourg City", "Esch-sur-Alzette"],
    region: "europe",
  },
  {
    code: "madagascar",
    name: "Madagascar",
    flag: "\u{1F1F2}\u{1F1EC}",
    iso: "MG",
    locations: ["Madagascar", "Antananarivo", "Toamasina", "Mahajanga"],
    region: "africa",
  },
  {
    code: "malawi",
    name: "Malawi",
    flag: "\u{1F1F2}\u{1F1FC}",
    iso: "MW",
    locations: ["Malawi", "Lilongwe", "Blantyre", "Mzuzu", "Zomba"],
    region: "africa",
  },
  {
    code: "malaysia",
    name: "Malaysia",
    flag: "\u{1F1F2}\u{1F1FE}",
    iso: "MY",
    locations: ["Malaysia", "Kuala Lumpur", "Johor Bahru", "Ipoh", "Kuching"],
    region: "southeast-asia",
  },
  {
    code: "maldives",
    name: "Maldives",
    flag: "\u{1F1F2}\u{1F1FB}",
    iso: "MV",
    locations: ["Maldives", "Mal\u00e9", "Addu City"],
    region: "south-asia",
  },
  {
    code: "mali",
    name: "Mali",
    flag: "\u{1F1F2}\u{1F1F1}",
    iso: "ML",
    locations: ["Mali", "Bamako", "Timbuktu", "S\u00e9gou", "Mopti"],
    region: "africa",
  },
  {
    code: "malta",
    name: "Malta",
    flag: "\u{1F1F2}\u{1F1F9}",
    iso: "MT",
    locations: ["Malta", "Valletta", "Sliema"],
    region: "europe",
  },
  {
    code: "mauritania",
    name: "Mauritania",
    flag: "\u{1F1F2}\u{1F1F7}",
    iso: "MR",
    locations: ["Mauritania", "Nouakchott", "Nouadhibou"],
    region: "arab",
  },
  {
    code: "mauritius",
    name: "Mauritius",
    flag: "\u{1F1F2}\u{1F1FA}",
    iso: "MU",
    locations: ["Mauritius", "Port Louis", "Curepipe", "Vacoas-Phoenix"],
    region: "africa",
  },
  {
    code: "mexico",
    name: "Mexico",
    flag: "\u{1F1F2}\u{1F1FD}",
    iso: "MX",
    locations: [
      "Mexico",
      "Mexico City",
      "Guadalajara",
      "Monterrey",
      "Puebla",
      "Tijuana",
    ],
    region: "latin-america",
  },
  {
    code: "moldova",
    name: "Moldova",
    flag: "\u{1F1F2}\u{1F1E9}",
    iso: "MD",
    locations: ["Moldova", "Chi\u0219in\u0103u", "Tiraspol"],
    region: "slavic",
  },
  {
    code: "mongolia",
    name: "Mongolia",
    flag: "\u{1F1F2}\u{1F1F3}",
    iso: "MN",
    locations: ["Mongolia", "Ulaanbaatar"],
    region: "east-asia",
  },
  {
    code: "montenegro",
    name: "Montenegro",
    flag: "\u{1F1F2}\u{1F1EA}",
    iso: "ME",
    locations: ["Montenegro", "Podgorica", "Nik\u0161i\u0107"],
    region: "slavic",
  },
  {
    code: "morocco",
    name: "Morocco",
    flag: "\u{1F1F2}\u{1F1E6}",
    iso: "MA",
    locations: [
      "Morocco",
      "Casablanca",
      "Tangier",
      "Marrakesh",
      "Rabat",
      "Fes",
    ],
    region: "arab",
  },
  {
    code: "mozambique",
    name: "Mozambique",
    flag: "\u{1F1F2}\u{1F1FF}",
    iso: "MZ",
    locations: ["Mozambique", "Maputo", "Beira", "Quelimane", "Matola"],
    region: "africa",
  },
  {
    code: "myanmar",
    name: "Myanmar",
    flag: "\u{1F1F2}\u{1F1F2}",
    iso: "MM",
    locations: ["Myanmar", "Yangon", "Mandalay", "Naypyidaw", "Bago"],
    region: "southeast-asia",
  },
  {
    code: "namibia",
    name: "Namibia",
    flag: "\u{1F1F3}\u{1F1E6}",
    iso: "NA",
    locations: ["Namibia", "Windhoek", "Swakopmund", "Walvis Bay"],
    region: "africa",
  },
  {
    code: "nepal",
    name: "Nepal",
    flag: "\u{1F1F3}\u{1F1F5}",
    iso: "NP",
    locations: ["Nepal", "Kathmandu", "Pokhara", "Lalitpur", "Biratnagar"],
    region: "south-asia",
  },
  {
    code: "netherlands",
    name: "Netherlands",
    flag: "\u{1F1F3}\u{1F1F1}",
    iso: "NL",
    locations: [
      "Netherlands",
      "Amsterdam",
      "Rotterdam",
      "The Hague",
      "Utrecht",
      "Eindhoven",
      "Groningen",
    ],
    region: "dutch",
  },
  {
    code: "new-zealand",
    name: "New Zealand",
    flag: "\u{1F1F3}\u{1F1FF}",
    iso: "NZ",
    locations: [
      "New Zealand",
      "Auckland",
      "Wellington",
      "Christchurch",
      "Dunedin",
    ],
    region: "english",
  },
  {
    code: "nicaragua",
    name: "Nicaragua",
    flag: "\u{1F1F3}\u{1F1EE}",
    iso: "NI",
    locations: ["Nicaragua", "Managua", "Le\u00f3n", "Masaya"],
    region: "latin-america",
  },
  {
    code: "nigeria",
    name: "Nigeria",
    flag: "\u{1F1F3}\u{1F1EC}",
    iso: "NG",
    locations: ["Nigeria", "Lagos", "Abuja", "Ibadan", "Port Harcourt", "Kano"],
    region: "africa",
  },
  {
    code: "norway",
    name: "Norway",
    flag: "\u{1F1F3}\u{1F1F4}",
    iso: "NO",
    locations: ["Norway", "Oslo", "Bergen", "Trondheim", "Stavanger"],
    region: "nordic",
  },
  {
    code: "oman",
    name: "Oman",
    flag: "\u{1F1F4}\u{1F1F2}",
    iso: "OM",
    locations: ["Oman", "Muscat", "Salalah", "Nizwa", "Sohar"],
    region: "arab",
  },
  {
    code: "pakistan",
    name: "Pakistan",
    flag: "\u{1F1F5}\u{1F1F0}",
    iso: "PK",
    locations: [
      "Pakistan",
      "Islamabad",
      "Karachi",
      "Lahore",
      "Faisalabad",
      "Peshawar",
    ],
    region: "south-asia",
  },
  {
    code: "palestine",
    name: "Palestine",
    flag: "\u{1F1F5}\u{1F1F8}",
    iso: "PS",
    locations: ["Palestine", "Gaza", "Hebron", "Nablus"],
    region: "arab",
  },
  {
    code: "panama",
    name: "Panama",
    flag: "\u{1F1F5}\u{1F1E6}",
    iso: "PA",
    locations: ["Panama", "Panama City"],
    region: "latin-america",
  },
  {
    code: "paraguay",
    name: "Paraguay",
    flag: "\u{1F1F5}\u{1F1FE}",
    iso: "PY",
    locations: [
      "Paraguay",
      "Asunci\u00f3n",
      "Ciudad del Este",
      "Encarnaci\u00f3n",
    ],
    region: "latin-america",
  },
  {
    code: "peru",
    name: "Peru",
    flag: "\u{1F1F5}\u{1F1EA}",
    iso: "PE",
    locations: ["Peru", "Lima", "Arequipa", "Cusco", "Chiclayo", "Piura"],
    region: "latin-america",
  },
  {
    code: "philippines",
    name: "Philippines",
    flag: "\u{1F1F5}\u{1F1ED}",
    iso: "PH",
    locations: [
      "Philippines",
      "Manila",
      "Quezon City",
      "Davao City",
      "Cebu City",
      "Makati",
    ],
    region: "southeast-asia",
  },
  {
    code: "poland",
    name: "Poland",
    flag: "\u{1F1F5}\u{1F1F1}",
    iso: "PL",
    locations: [
      "Poland",
      "Warsaw",
      "Krak\u00f3w",
      "Wroc\u0142aw",
      "Gda\u0144sk",
      "Pozna\u0144",
    ],
    region: "slavic",
  },
  {
    code: "portugal",
    name: "Portugal",
    flag: "\u{1F1F5}\u{1F1F9}",
    iso: "PT",
    locations: ["Portugal", "Lisbon", "Porto", "Braga", "Coimbra"],
    region: "portuguese",
  },
  {
    code: "qatar",
    name: "Qatar",
    flag: "\u{1F1F6}\u{1F1E6}",
    iso: "QA",
    locations: ["Qatar", "Doha"],
    region: "arab",
  },
  {
    code: "romania",
    name: "Romania",
    flag: "\u{1F1F7}\u{1F1F4}",
    iso: "RO",
    locations: [
      "Romania",
      "Bucharest",
      "Constan\u021ba",
      "Cluj-Napoca",
      "Timi\u0219oara",
    ],
    region: "europe",
  },
  {
    code: "russia",
    name: "Russia",
    flag: "\u{1F1F7}\u{1F1FA}",
    iso: "RU",
    locations: [
      "Russia",
      "Moscow",
      "Saint Petersburg",
      "Yekaterinburg",
      "Novosibirsk",
      "Kazan",
    ],
    region: "slavic",
  },
  {
    code: "rwanda",
    name: "Rwanda",
    flag: "\u{1F1F7}\u{1F1FC}",
    iso: "RW",
    locations: ["Rwanda", "Kigali"],
    region: "africa",
  },
  {
    code: "san-marino",
    name: "San Marino",
    flag: "\u{1F1F8}\u{1F1F2}",
    iso: "SM",
    locations: ["San Marino"],
    region: "italian",
  },
  {
    code: "saudi-arabia",
    name: "Saudi Arabia",
    flag: "\u{1F1F8}\u{1F1E6}",
    iso: "SA",
    locations: [
      "Saudi Arabia",
      "Riyadh",
      "Jeddah",
      "Mecca",
      "Medina",
      "Dammam",
    ],
    region: "arab",
  },
  {
    code: "senegal",
    name: "Senegal",
    flag: "\u{1F1F8}\u{1F1F3}",
    iso: "SN",
    locations: ["Senegal", "Dakar"],
    region: "africa",
  },
  {
    code: "serbia",
    name: "Serbia",
    flag: "\u{1F1F7}\u{1F1F8}",
    iso: "RS",
    locations: ["Serbia", "Belgrade", "Novi Sad", "Ni\u0161"],
    region: "slavic",
  },
  {
    code: "sierra-leone",
    name: "Sierra Leone",
    flag: "\u{1F1F8}\u{1F1F1}",
    iso: "SL",
    locations: ["Sierra Leone", "Freetown"],
    region: "africa",
  },
  {
    code: "singapore",
    name: "Singapore",
    flag: "\u{1F1F8}\u{1F1EC}",
    iso: "SG",
    locations: ["Singapore"],
    region: "southeast-asia",
  },
  {
    code: "slovakia",
    name: "Slovakia",
    flag: "\u{1F1F8}\u{1F1F0}",
    iso: "SK",
    locations: ["Slovakia", "Bratislava", "Ko\u0161ice"],
    region: "slavic",
  },
  {
    code: "slovenia",
    name: "Slovenia",
    flag: "\u{1F1F8}\u{1F1EE}",
    iso: "SI",
    locations: ["Slovenia", "Ljubljana", "Maribor", "Koper", "Celje"],
    region: "slavic",
  },
  {
    code: "south-africa",
    name: "South Africa",
    flag: "\u{1F1FF}\u{1F1E6}",
    iso: "ZA",
    locations: [
      "South Africa",
      "Cape Town",
      "Johannesburg",
      "Durban",
      "Pretoria",
    ],
    region: "africa",
  },
  {
    code: "south-korea",
    name: "South Korea",
    flag: "\u{1F1F0}\u{1F1F7}",
    iso: "KR",
    locations: ["South Korea", "Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
    region: "korean",
  },
  {
    code: "spain",
    name: "Spain",
    flag: "\u{1F1EA}\u{1F1F8}",
    iso: "ES",
    locations: [
      "Spain",
      "Madrid",
      "Barcelona",
      "Seville",
      "Valencia",
      "Bilbao",
    ],
    region: "spanish",
  },
  {
    code: "sri-lanka",
    name: "Sri Lanka",
    flag: "\u{1F1F1}\u{1F1F0}",
    iso: "LK",
    locations: ["Sri Lanka", "Colombo", "Kandy", "Galle", "Jaffna"],
    region: "south-asia",
  },
  {
    code: "sudan",
    name: "Sudan",
    flag: "\u{1F1F8}\u{1F1E9}",
    iso: "SD",
    locations: ["Sudan", "Khartoum", "Omdurman"],
    region: "arab",
  },
  {
    code: "sweden",
    name: "Sweden",
    flag: "\u{1F1F8}\u{1F1EA}",
    iso: "SE",
    locations: ["Sweden", "Stockholm", "Gothenburg", "Uppsala", "Malm\u00f6"],
    region: "nordic",
  },
  {
    code: "switzerland",
    name: "Switzerland",
    flag: "\u{1F1E8}\u{1F1ED}",
    iso: "CH",
    locations: [
      "Switzerland",
      "Z\u00fcrich",
      "Geneva",
      "Basel",
      "Lausanne",
      "Bern",
    ],
    region: "german",
  },
  {
    code: "syria",
    name: "Syria",
    flag: "\u{1F1F8}\u{1F1FE}",
    iso: "SY",
    locations: ["Syria", "Damascus", "Aleppo", "Homs", "Latakia"],
    region: "arab",
  },
  {
    code: "tanzania",
    name: "Tanzania",
    flag: "\u{1F1F9}\u{1F1FF}",
    iso: "TZ",
    locations: ["Tanzania", "Dar es Salaam", "Dodoma", "Mwanza"],
    region: "africa",
  },
  {
    code: "thailand",
    name: "Thailand",
    flag: "\u{1F1F9}\u{1F1ED}",
    iso: "TH",
    locations: ["Thailand", "Bangkok", "Chiang Mai", "Phuket", "Pattaya"],
    region: "southeast-asia",
  },
  {
    code: "tunisia",
    name: "Tunisia",
    flag: "\u{1F1F9}\u{1F1F3}",
    iso: "TN",
    locations: ["Tunisia", "Tunis", "Sfax", "Sousse"],
    region: "arab",
  },
  {
    code: "turkey",
    name: "Turkey",
    flag: "\u{1F1F9}\u{1F1F7}",
    iso: "TR",
    locations: [
      "Turkey",
      "Istanbul",
      "Ankara",
      "Izmir",
      "Konya",
      "Gaziantep",
      "Adana",
    ],
    region: "turkic",
  },
  {
    code: "uganda",
    name: "Uganda",
    flag: "\u{1F1FA}\u{1F1EC}",
    iso: "UG",
    locations: ["Uganda", "Kampala"],
    region: "africa",
  },
  {
    code: "ukraine",
    name: "Ukraine",
    flag: "\u{1F1FA}\u{1F1E6}",
    iso: "UA",
    locations: ["Ukraine", "Kyiv", "Lviv", "Kharkiv", "Odesa"],
    region: "slavic",
  },
  {
    code: "united-arab-emirates",
    name: "United Arab Emirates",
    flag: "\u{1F1E6}\u{1F1EA}",
    iso: "AE",
    locations: [
      "United Arab Emirates",
      "Dubai",
      "Abu Dhabi",
      "Sharjah",
      "Ajman",
    ],
    region: "arab",
  },
  {
    code: "united-kingdom",
    name: "United Kingdom",
    flag: "\u{1F1EC}\u{1F1E7}",
    iso: "GB",
    locations: [
      "United Kingdom",
      "London",
      "Manchester",
      "Cambridge",
      "Edinburgh",
      "Birmingham",
      "Bristol",
    ],
    region: "english",
  },
  {
    code: "united-states",
    name: "United States",
    flag: "\u{1F1FA}\u{1F1F8}",
    iso: "US",
    locations: [
      "San Francisco",
      "New York",
      "Seattle",
      "Austin",
      "Los Angeles",
      "Chicago",
      "Boston",
    ],
    region: "english",
  },
  {
    code: "uruguay",
    name: "Uruguay",
    flag: "\u{1F1FA}\u{1F1FE}",
    iso: "UY",
    locations: ["Uruguay", "Montevideo"],
    region: "latin-america",
  },
  {
    code: "uzbekistan",
    name: "Uzbekistan",
    flag: "\u{1F1FA}\u{1F1FF}",
    iso: "UZ",
    locations: ["Uzbekistan", "Tashkent", "Samarkand"],
    region: "turkic",
  },
  {
    code: "venezuela",
    name: "Venezuela",
    flag: "\u{1F1FB}\u{1F1EA}",
    iso: "VE",
    locations: ["Venezuela", "Caracas", "Maracaibo", "Maracay"],
    region: "latin-america",
  },
  {
    code: "vietnam",
    name: "Vietnam",
    flag: "\u{1F1FB}\u{1F1F3}",
    iso: "VN",
    locations: [
      "Vietnam",
      "Ho Chi Minh City",
      "Hanoi",
      "Da Nang",
      "Can Tho",
      "Haiphong",
    ],
    region: "southeast-asia",
  },
  {
    code: "yemen",
    name: "Yemen",
    flag: "\u{1F1FE}\u{1F1EA}",
    iso: "YE",
    locations: ["Yemen", "Sana'a"],
    region: "arab",
  },
  {
    code: "zambia",
    name: "Zambia",
    flag: "\u{1F1FF}\u{1F1F2}",
    iso: "ZM",
    locations: ["Zambia", "Lusaka"],
    region: "africa",
  },
  {
    code: "zimbabwe",
    name: "Zimbabwe",
    flag: "\u{1F1FF}\u{1F1FC}",
    iso: "ZW",
    locations: ["Zimbabwe", "Harare", "Bulawayo"],
    region: "africa",
  },

  // Additional 57 countries to reach 195
  {
    code: "antigua-and-barbuda",
    name: "Antigua and Barbuda",
    flag: "\u{1F1E6}\u{1F1EC}",
    iso: "AG",
    locations: ["Antigua and Barbuda", "St. John's"],
    region: "english",
  },
  {
    code: "bahamas",
    name: "Bahamas",
    flag: "\u{1F1E7}\u{1F1F8}",
    iso: "BS",
    locations: ["Bahamas", "Nassau", "Freeport"],
    region: "english",
  },
  {
    code: "barbados",
    name: "Barbados",
    flag: "\u{1F1E7}\u{1F1E7}",
    iso: "BB",
    locations: ["Barbados", "Bridgetown"],
    region: "english",
  },
  {
    code: "belize",
    name: "Belize",
    flag: "\u{1F1E7}\u{1F1FF}",
    iso: "BZ",
    locations: ["Belize", "Belmopan", "Belize City"],
    region: "english",
  },
  {
    code: "cabo-verde",
    name: "Cabo Verde",
    flag: "\u{1F1E8}\u{1F1FB}",
    iso: "CV",
    locations: ["Cabo Verde", "Praia"],
    region: "portuguese",
  },
  {
    code: "central-african-republic",
    name: "Central African Republic",
    flag: "\u{1F1E8}\u{1F1EB}",
    iso: "CF",
    locations: ["Central African Republic", "Bangui"],
    region: "africa",
  },
  {
    code: "comoros",
    name: "Comoros",
    flag: "\u{1F1F0}\u{1F1F2}",
    iso: "KM",
    locations: ["Comoros", "Moroni"],
    region: "africa",
  },
  {
    code: "costa-rica",
    name: "Costa Rica",
    flag: "\u{1F1E8}\u{1F1F7}",
    iso: "CR",
    locations: ["Costa Rica", "San Jos\u00e9"],
    region: "latin-america",
  },
  {
    code: "cote-d-ivoire",
    name: "C\u00f4te d'Ivoire",
    flag: "\u{1F1E8}\u{1F1EE}",
    iso: "CI",
    locations: ["C\u00f4te d'Ivoire", "Abidjan", "Yamoussoukro"],
    region: "africa",
  },
  {
    code: "democratic-republic-of-the-congo",
    name: "Dem. Rep. Congo",
    flag: "\u{1F1E8}\u{1F1E9}",
    iso: "CD",
    locations: ["Democratic Republic of the Congo", "Kinshasa", "Lubumbashi"],
    region: "africa",
  },
  {
    code: "djibouti",
    name: "Djibouti",
    flag: "\u{1F1E9}\u{1F1EF}",
    iso: "DJ",
    locations: ["Djibouti", "Djibouti City"],
    region: "africa",
  },
  {
    code: "dominica",
    name: "Dominica",
    flag: "\u{1F1E9}\u{1F1F2}",
    iso: "DM",
    locations: ["Dominica", "Roseau"],
    region: "english",
  },
  {
    code: "equatorial-guinea",
    name: "Equatorial Guinea",
    flag: "\u{1F1EC}\u{1F1F6}",
    iso: "GQ",
    locations: ["Equatorial Guinea", "Malabo"],
    region: "africa",
  },
  {
    code: "eritrea",
    name: "Eritrea",
    flag: "\u{1F1EA}\u{1F1F7}",
    iso: "ER",
    locations: ["Eritrea", "Asmara"],
    region: "africa",
  },
  {
    code: "eswatini",
    name: "Eswatini",
    flag: "\u{1F1F8}\u{1F1FF}",
    iso: "SZ",
    locations: ["Eswatini", "Mbabane", "Manzini"],
    region: "africa",
  },
  {
    code: "fiji",
    name: "Fiji",
    flag: "\u{1F1EB}\u{1F1EF}",
    iso: "FJ",
    locations: ["Fiji", "Suva", "Nadi"],
    region: "english",
  },
  {
    code: "gabon",
    name: "Gabon",
    flag: "\u{1F1EC}\u{1F1E6}",
    iso: "GA",
    locations: ["Gabon", "Libreville"],
    region: "africa",
  },
  {
    code: "gambia",
    name: "Gambia",
    flag: "\u{1F1EC}\u{1F1F2}",
    iso: "GM",
    locations: ["Gambia", "Banjul"],
    region: "africa",
  },
  {
    code: "grenada",
    name: "Grenada",
    flag: "\u{1F1EC}\u{1F1E9}",
    iso: "GD",
    locations: ["Grenada", "St. George's"],
    region: "english",
  },
  {
    code: "guinea",
    name: "Guinea",
    flag: "\u{1F1EC}\u{1F1F3}",
    iso: "GN",
    locations: ["Guinea", "Conakry"],
    region: "africa",
  },
  {
    code: "guinea-bissau",
    name: "Guinea-Bissau",
    flag: "\u{1F1EC}\u{1F1FC}",
    iso: "GW",
    locations: ["Guinea-Bissau", "Bissau"],
    region: "africa",
  },
  {
    code: "guyana",
    name: "Guyana",
    flag: "\u{1F1EC}\u{1F1FE}",
    iso: "GY",
    locations: ["Guyana", "Georgetown"],
    region: "english",
  },
  {
    code: "haiti",
    name: "Haiti",
    flag: "\u{1F1ED}\u{1F1F9}",
    iso: "HT",
    locations: ["Haiti", "Port-au-Prince"],
    region: "french",
  },
  {
    code: "kiribati",
    name: "Kiribati",
    flag: "\u{1F1F0}\u{1F1EE}",
    iso: "KI",
    locations: ["Kiribati", "Tarawa"],
    region: "english",
  },
  {
    code: "kyrgyzstan",
    name: "Kyrgyzstan",
    flag: "\u{1F1F0}\u{1F1EC}",
    iso: "KG",
    locations: ["Kyrgyzstan", "Bishkek", "Osh"],
    region: "turkic",
  },
  {
    code: "lebanon",
    name: "Lebanon",
    flag: "\u{1F1F1}\u{1F1E7}",
    iso: "LB",
    locations: ["Lebanon", "Beirut", "Tripoli"],
    region: "arab",
  },
  {
    code: "lesotho",
    name: "Lesotho",
    flag: "\u{1F1F1}\u{1F1F8}",
    iso: "LS",
    locations: ["Lesotho", "Maseru"],
    region: "africa",
  },
  {
    code: "liberia",
    name: "Liberia",
    flag: "\u{1F1F1}\u{1F1F7}",
    iso: "LR",
    locations: ["Liberia", "Monrovia"],
    region: "africa",
  },
  {
    code: "libya",
    name: "Libya",
    flag: "\u{1F1F1}\u{1F1FE}",
    iso: "LY",
    locations: ["Libya", "Tripoli", "Benghazi"],
    region: "arab",
  },
  {
    code: "liechtenstein",
    name: "Liechtenstein",
    flag: "\u{1F1F1}\u{1F1EE}",
    iso: "LI",
    locations: ["Liechtenstein", "Vaduz"],
    region: "german",
  },
  {
    code: "marshall-islands",
    name: "Marshall Islands",
    flag: "\u{1F1F2}\u{1F1ED}",
    iso: "MH",
    locations: ["Marshall Islands", "Majuro"],
    region: "english",
  },
  {
    code: "micronesia",
    name: "Micronesia",
    flag: "\u{1F1EB}\u{1F1F2}",
    iso: "FM",
    locations: ["Micronesia", "Palikir"],
    region: "english",
  },
  {
    code: "monaco",
    name: "Monaco",
    flag: "\u{1F1F2}\u{1F1E8}",
    iso: "MC",
    locations: ["Monaco", "Monte Carlo"],
    region: "french",
  },
  {
    code: "nauru",
    name: "Nauru",
    flag: "\u{1F1F3}\u{1F1F7}",
    iso: "NR",
    locations: ["Nauru", "Yaren"],
    region: "english",
  },
  {
    code: "niger",
    name: "Niger",
    flag: "\u{1F1F3}\u{1F1EA}",
    iso: "NE",
    locations: ["Niger", "Niamey"],
    region: "africa",
  },
  {
    code: "north-korea",
    name: "North Korea",
    flag: "\u{1F1F0}\u{1F1F5}",
    iso: "KP",
    locations: ["North Korea", "Pyongyang"],
    region: "korean",
  },
  {
    code: "north-macedonia",
    name: "North Macedonia",
    flag: "\u{1F1F2}\u{1F1F0}",
    iso: "MK",
    locations: ["North Macedonia", "Skopje", "Bitola"],
    region: "slavic",
  },
  {
    code: "palau",
    name: "Palau",
    flag: "\u{1F1F5}\u{1F1FC}",
    iso: "PW",
    locations: ["Palau", "Ngerulmud"],
    region: "english",
  },
  {
    code: "papua-new-guinea",
    name: "Papua New Guinea",
    flag: "\u{1F1F5}\u{1F1EC}",
    iso: "PG",
    locations: ["Papua New Guinea", "Port Moresby"],
    region: "english",
  },
  {
    code: "saint-kitts-and-nevis",
    name: "Saint Kitts and Nevis",
    flag: "\u{1F1F0}\u{1F1F3}",
    iso: "KN",
    locations: ["Saint Kitts and Nevis", "Basseterre"],
    region: "english",
  },
  {
    code: "saint-lucia",
    name: "Saint Lucia",
    flag: "\u{1F1F1}\u{1F1E8}",
    iso: "LC",
    locations: ["Saint Lucia", "Castries"],
    region: "english",
  },
  {
    code: "saint-vincent-and-the-grenadines",
    name: "Saint Vincent and the Grenadines",
    flag: "\u{1F1FB}\u{1F1E8}",
    iso: "VC",
    locations: ["Saint Vincent and the Grenadines", "Kingstown"],
    region: "english",
  },
  {
    code: "samoa",
    name: "Samoa",
    flag: "\u{1F1FC}\u{1F1F8}",
    iso: "WS",
    locations: ["Samoa", "Apia"],
    region: "english",
  },
  {
    code: "sao-tome-and-principe",
    name: "S\u00e3o Tom\u00e9 and Pr\u00edncipe",
    flag: "\u{1F1F8}\u{1F1F9}",
    iso: "ST",
    locations: ["S\u00e3o Tom\u00e9 and Pr\u00edncipe", "S\u00e3o Tom\u00e9"],
    region: "portuguese",
  },
  {
    code: "seychelles",
    name: "Seychelles",
    flag: "\u{1F1F8}\u{1F1E8}",
    iso: "SC",
    locations: ["Seychelles", "Victoria"],
    region: "english",
  },
  {
    code: "solomon-islands",
    name: "Solomon Islands",
    flag: "\u{1F1F8}\u{1F1E7}",
    iso: "SB",
    locations: ["Solomon Islands", "Honiara"],
    region: "english",
  },
  {
    code: "somalia",
    name: "Somalia",
    flag: "\u{1F1F8}\u{1F1F4}",
    iso: "SO",
    locations: ["Somalia", "Mogadishu", "Hargeisa"],
    region: "africa",
  },
  {
    code: "south-sudan",
    name: "South Sudan",
    flag: "\u{1F1F8}\u{1F1F8}",
    iso: "SS",
    locations: ["South Sudan", "Juba"],
    region: "africa",
  },
  {
    code: "suriname",
    name: "Suriname",
    flag: "\u{1F1F8}\u{1F1F7}",
    iso: "SR",
    locations: ["Suriname", "Paramaribo"],
    region: "dutch",
  },
  {
    code: "tajikistan",
    name: "Tajikistan",
    flag: "\u{1F1F9}\u{1F1EF}",
    iso: "TJ",
    locations: ["Tajikistan", "Dushanbe"],
    region: "persian",
  },
  {
    code: "timor-leste",
    name: "Timor-Leste",
    flag: "\u{1F1F9}\u{1F1F1}",
    iso: "TL",
    locations: ["Timor-Leste", "Dili"],
    region: "southeast-asia",
  },
  {
    code: "togo",
    name: "Togo",
    flag: "\u{1F1F9}\u{1F1EC}",
    iso: "TG",
    locations: ["Togo", "Lom\u00e9"],
    region: "africa",
  },
  {
    code: "tonga",
    name: "Tonga",
    flag: "\u{1F1F9}\u{1F1F4}",
    iso: "TO",
    locations: ["Tonga", "Nuku'alofa"],
    region: "english",
  },
  {
    code: "trinidad-and-tobago",
    name: "Trinidad and Tobago",
    flag: "\u{1F1F9}\u{1F1F9}",
    iso: "TT",
    locations: ["Trinidad and Tobago", "Port of Spain"],
    region: "english",
  },
  {
    code: "turkmenistan",
    name: "Turkmenistan",
    flag: "\u{1F1F9}\u{1F1F2}",
    iso: "TM",
    locations: ["Turkmenistan", "Ashgabat"],
    region: "turkic",
  },
  {
    code: "tuvalu",
    name: "Tuvalu",
    flag: "\u{1F1F9}\u{1F1FB}",
    iso: "TV",
    locations: ["Tuvalu", "Funafuti"],
    region: "english",
  },
  {
    code: "vanuatu",
    name: "Vanuatu",
    flag: "\u{1F1FB}\u{1F1FA}",
    iso: "VU",
    locations: ["Vanuatu", "Port Vila"],
    region: "english",
  },
];

// Region-based name pools for culturally appropriate names
const regionNames: Record<string, string[]> = {
  english: [
    "alex-johnson",
    "jordan-smith",
    "taylor-williams",
    "casey-brown",
    "morgan-jones",
    "riley-davis",
    "avery-miller",
    "quinn-wilson",
    "blake-moore",
    "drew-anderson",
  ],
  french: [
    "lucas-martin",
    "hugo-bernard",
    "louis-dubois",
    "raphael-thomas",
    "gabriel-robert",
    "arthur-richard",
    "jules-petit",
    "adam-durand",
    "leo-leroy",
    "noah-moreau",
  ],
  german: [
    "lukas-mueller",
    "leon-schmidt",
    "finn-weber",
    "paul-wagner",
    "jonas-becker",
    "felix-hoffmann",
    "elias-schulz",
    "noah-fischer",
    "lina-koch",
    "emma-bauer",
  ],
  spanish: [
    "carlos-garcia",
    "diego-martinez",
    "alejandro-lopez",
    "sofia-hernandez",
    "lucia-rodriguez",
    "maria-gonzalez",
    "pablo-sanchez",
    "javier-ramirez",
    "ana-torres",
    "miguel-flores",
  ],
  italian: [
    "luca-rossi",
    "marco-russo",
    "giuseppe-ferrari",
    "andrea-esposito",
    "matteo-bianchi",
    "alessandro-romano",
    "davide-colombo",
    "lorenzo-ricci",
    "chiara-marino",
    "giulia-greco",
  ],
  portuguese: [
    "pedro-silva",
    "lucas-santos",
    "gabriel-oliveira",
    "miguel-souza",
    "rafael-costa",
    "matheus-pereira",
    "davi-rodrigues",
    "arthur-almeida",
    "bernardo-lima",
    "joao-ferreira",
  ],
  "latin-america": [
    "carlos-garcia",
    "diego-martinez",
    "alejandro-lopez",
    "sofia-hernandez",
    "lucia-rodriguez",
    "pablo-sanchez",
    "javier-ramirez",
    "ana-torres",
    "miguel-flores",
    "valentina-reyes",
  ],
  slavic: [
    "ivan-petrov",
    "dmitri-sokolov",
    "alexei-popov",
    "nikolai-volkov",
    "sergei-kozlov",
    "andrei-novikov",
    "mikhail-morozov",
    "anton-pavlov",
    "yuri-lebedev",
    "boris-egorov",
  ],
  nordic: [
    "erik-johansson",
    "lars-anderson",
    "nils-hansen",
    "gustav-lindberg",
    "olaf-nilsen",
    "astrid-larsen",
    "sigrid-berg",
    "freya-dahl",
    "magnus-holm",
    "ingrid-moen",
  ],
  dutch: [
    "jan-de-vries",
    "pieter-jansen",
    "thomas-bakker",
    "lucas-visser",
    "daan-smit",
    "bram-mulder",
    "sem-de-boer",
    "finn-dekker",
    "julia-bos",
    "emma-dijkstra",
  ],
  chinese: [
    "wei-chen",
    "ming-hao",
    "jia-ling",
    "yu-ting",
    "zhi-wei",
    "kai-wen",
    "hao-yang",
    "xin-yi",
    "jun-hao",
    "shu-ting",
  ],
  japanese: [
    "yuki-tanaka",
    "haruto-sato",
    "aoi-suzuki",
    "ren-takahashi",
    "sakura-ito",
    "sora-yamamoto",
    "hina-watanabe",
    "riku-nakamura",
    "mio-kobayashi",
    "yuto-kato",
  ],
  korean: [
    "min-jun-kim",
    "seo-yeon-lee",
    "ji-ho-park",
    "ha-yoon-choi",
    "do-yun-jung",
    "ye-jun-kang",
    "soo-ah-cho",
    "joon-woo-yoon",
    "si-woo-lim",
    "ji-yeon-han",
  ],
  "south-asia": [
    "aarav-sharma",
    "vihaan-patel",
    "aditya-kumar",
    "arjun-singh",
    "reyansh-gupta",
    "vivaan-joshi",
    "ananya-reddy",
    "isha-verma",
    "priya-nair",
    "rohan-das",
  ],
  "southeast-asia": [
    "wei-jie-tan",
    "xin-yi-ng",
    "jun-hao-lim",
    "thanh-nguyen",
    "somchai-wong",
    "adi-pratama",
    "budi-santoso",
    "rizal-ahmad",
    "maria-santos",
    "putri-dewi",
  ],
  arab: [
    "ahmed-ali",
    "mohammed-hassan",
    "omar-ibrahim",
    "youssef-mahmoud",
    "khalid-abdullah",
    "fatima-zahra",
    "nour-al-din",
    "tariq-saeed",
    "layla-nasir",
    "hassan-mansour",
  ],
  persian: [
    "reza-hosseini",
    "ali-mohammadi",
    "mehdi-karimi",
    "sara-ahmadi",
    "amir-rahimi",
    "parsa-moradi",
    "nima-jafari",
    "dariush-taheri",
    "shirin-kazemi",
    "kaveh-rostami",
  ],
  turkic: [
    "emre-yilmaz",
    "ahmet-kaya",
    "mehmet-demir",
    "ayse-celik",
    "fatma-sahin",
    "mustafa-ozturk",
    "zeynep-arslan",
    "burak-dogan",
    "elif-yildiz",
    "cem-polat",
  ],
  hebrew: [
    "noam-cohen",
    "yael-levy",
    "ori-shapira",
    "adi-mizrahi",
    "tal-peretz",
    "lior-katz",
    "gal-avraham",
    "noa-goldstein",
    "eitan-rosen",
    "shira-david",
  ],
  baltic: [
    "janis-berzins",
    "kristaps-ozols",
    "maris-kalns",
    "andris-liepins",
    "gatis-vitols",
    "liga-abele",
    "daina-ozola",
    "ilze-strazdina",
    "ainis-lapins",
    "ruta-kazlauskas",
  ],
  africa: [
    "kwame-asante",
    "amina-osei",
    "chidi-okafor",
    "fatou-diallo",
    "kofi-mensah",
    "ayo-oluwaseun",
    "tendai-moyo",
    "wanjiku-kamau",
    "jabari-mwangi",
    "amara-sesay",
  ],
  "east-asia": [
    "bold-bataar",
    "ganzorig-erdene",
    "bat-erdene-tsog",
    "munkh-dulam",
    "enkhtuya-dash",
    "ganbaatar-sukhee",
    "tsolmon-bayar",
    "erdenechimeg-bold",
    "oyunbileg-batbold",
    "altantsetseg-ganbat",
  ],
};

const LANGUAGES = [
  "TypeScript",
  "JavaScript",
  "Python",
  "Go",
  "Rust",
  "Java",
  "C++",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Dart",
];

const COMPANIES = [
  "Google",
  "Microsoft",
  "Amazon",
  "Meta",
  "Apple",
  "GitHub",
  "Vercel",
  "Stripe",
  null,
  null,
  null,
  null,
];

function rand(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function pickRandom<T>(arr: T[], count: number): T[] {
  const shuffled = [...arr].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

function getNamePool(region: string): string[] {
  return regionNames[region] || regionNames.english;
}

interface UserData {
  login: string;
  avatarUrl: string;
  name: string;
  company: string | null;
  location: string;
  bio: string | null;
  followers: number;
  publicContributions: number;
  privateContributions: number;
  languages: string[];
  topRepos: { name: string; stars: number; language: string }[];
  twitterUsername: string | null;
  blog: string | null;
}

function generateUsers(country: CountryDef, countryIndex: number): UserData[] {
  const namePool = getNamePool(country.region);
  const users: UserData[] = [];
  for (let i = 0; i < 100; i++) {
    const decay = Math.exp(-i * 0.04);
    const baseName = namePool[i % namePool.length];
    const suffix = i >= 10 ? `-${i}` : "";
    const login = `${baseName}${suffix}`;
    const pubContrib = Math.round(35000 * decay + rand(50, 200));
    const privContrib = rand(0, 500);
    const followers = Math.round(5000 * decay + rand(10, 50));
    const langs = pickRandom(LANGUAGES, rand(1, 4));
    const topRepoCount = rand(1, 3);
    const topRepos = Array.from({ length: topRepoCount }, (_, j) => ({
      name: `${login.split("-")[0]}-project-${j + 1}`,
      stars: Math.round(2000 * decay * Math.random() + rand(5, 50)),
      language: langs[j % langs.length],
    }));

    users.push({
      login,
      avatarUrl: `https://avatars.githubusercontent.com/u/${countryIndex * 1000 + i}?v=4`,
      name: login
        .split("-")
        .map((w: string) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(" "),
      company: COMPANIES[rand(0, COMPANIES.length - 1)],
      location: country.locations[rand(0, country.locations.length - 1)],
      bio: i < 30 ? `Full-stack developer from ${country.name}` : null,
      followers,
      publicContributions: pubContrib,
      privateContributions: privContrib,
      languages: langs,
      topRepos,
      twitterUsername: i < 20 ? login : null,
      blog: i < 15 ? `https://${login}.dev` : null,
    });
  }
  return users;
}

// Generate all files
for (let c = 0; c < countries.length; c++) {
  const country = countries[c];
  const startId = c;

  const configPath = path.join("config", "countries", `${country.code}.json`);
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.writeFileSync(
    configPath,
    JSON.stringify(
      {
        code: country.code,
        name: country.name,
        flag: country.flag,
        locations: country.locations,
      },
      null,
      2,
    ),
  );

  const users = generateUsers(country, startId);
  const byPub = [...users].sort(
    (a, b) => b.publicContributions - a.publicContributions,
  );
  const byTotal = [...users].sort(
    (a, b) =>
      b.publicContributions +
      b.privateContributions -
      (a.publicContributions + a.privateContributions),
  );
  const byFollowers = [...users].sort((a, b) => b.followers - a.followers);

  const dataPath = path.join("data", `${country.code}.json`);
  fs.mkdirSync(path.dirname(dataPath), { recursive: true });
  fs.writeFileSync(
    dataPath,
    JSON.stringify(
      {
        countryCode: country.code,
        updatedAt: "2026-03-28T00:00:00.000Z",
        users: [],
        rankings: {
          public_contributions: byPub,
          total_contributions: byTotal,
          followers: byFollowers,
        },
      },
      null,
      2,
    ),
  );

  console.log(`\u2713 ${country.flag} ${country.name}: ${users.length} users`);
}

console.log(`\nDone! Generated data for ${countries.length} countries.`);
